env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends: airbnb-base
overrides: 
  - files:
    - test/**/*.js
    rules:
      func-names: off
      prefer-arrow-callback: off
parserOptions:
  ecmaVersion: latest
rules: {'no-unused-vars': ['error', { argsIgnorePattern: 'next' }]}
