name: fake main branch action 
on: 
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

  

jobs:
  fake-main-job:
    runs-on: ubuntu-latest

    steps:
      - name: echo main branch
        run: "echo now deploying to production"
