name: main test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  mocha-supertest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Mocha and supertest
        run: npm run test
